"""
AI-BOS — PDF rendering for payslips + compliance packs (audit #26/#66).

A tiny wrapper over reportlab that turns the SAME text documents payroll.py
already produces (payslip_text / compliance_text) into a clean A5/A4 PDF. The
text version is the source of truth (WhatsApp-shareable); the PDF is the
printable/keepable artefact accountants and auditors expect.

reportlab is imported LAZILY inside render(), so `import main` never fails if
the lib is missing in some environment — the route falls back to serving the
text as a .txt attachment (available() tells the caller which they'll get).
Markdown-lite (*bold*) from the text is stripped for the PDF.
"""

import io
import re


def available() -> bool:
    try:
        import reportlab  # noqa: F401
        return True
    except Exception:  # noqa: BLE001
        return False


def _clean(line: str) -> tuple[str, bool]:
    """Strip *bold* markers; return (text, is_bold) — bold if the whole line was."""
    bold = line.strip().startswith("*") and line.strip().endswith("*")
    return re.sub(r"\*", "", line), bold


def render(title: str, body_text: str) -> bytes:
    """Render a plain text document (newline-separated, *bold* lines) to PDF bytes."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    x = 22 * mm
    y = height - 28 * mm

    c.setFont("Helvetica-Bold", 15)
    c.drawString(x, y, title)
    y -= 6 * mm
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.line(x, y, width - 22 * mm, y)
    y -= 8 * mm

    for raw in body_text.splitlines():
        if y < 25 * mm:                       # new page
            c.showPage()
            y = height - 28 * mm
        text, bold = _clean(raw)
        if not text.strip():
            y -= 4 * mm
            continue
        c.setFont("Helvetica-Bold" if bold else "Helvetica", 11 if bold else 10)
        c.drawString(x, y, text[:110])
        y -= 6 * mm

    c.setFont("Helvetica-Oblique", 8)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(x, 15 * mm, "Generated by AIBOS — figures computed from your recorded data.")
    c.showPage()
    c.save()
    return buf.getvalue()
