"""
AIBOS — PDF rendering for payslips + compliance packs (audit #26/#66).

A tiny wrapper over reportlab that turns the SAME text documents payroll.py
already produces (payslip_text / compliance_text) into a clean A5/A4 PDF. The
text version is the source of truth (WhatsApp-shareable); the PDF is the
printable/keepable artefact accountants and auditors expect.

reportlab is imported LAZILY inside render(), so `import main` never fails if
the lib is missing in some environment — the route falls back to serving the
text as a .txt attachment (available() tells the caller which they'll get).
Markdown-lite (*bold*) from the text is stripped for the PDF.
"""

import io
import os
import re

# The AIBOS mark in grey, for the footer of every page (the owner, 5 Oct 2026:
# "add the aibos logo to the bottom of the statutory pdf report in grey like
# the words"). Made from the app's mark (aibos/public/brand/aibos-mark.png),
# its colours turned to the footer's grey.
_LOGO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "brand", "aibos-mark-grey.png")
FOOTER = "Generated by AIBOS from your recorded figures."


def available() -> bool:
    try:
        import reportlab  # noqa: F401
        return True
    except Exception:  # noqa: BLE001
        return False


def _clean(line: str) -> tuple[str, bool]:
    """Strip *bold* markers; return (text, is_bold) — bold if the whole line was."""
    bold = line.strip().startswith("*") and line.strip().endswith("*")
    return re.sub(r"\*", "", line), bold


def _footer(c, x: float, mm: float) -> None:
    """The grey AIBOS mark with the grey words beside it, on the page's foot."""
    c.saveState()
    text_x = x
    if os.path.exists(_LOGO):
        try:
            from reportlab.lib.utils import ImageReader
            logo = ImageReader(_LOGO)
            lw, lh = logo.getSize()
            h = 5.2 * mm
            w = h * lw / lh
            c.drawImage(logo, x, 13.4 * mm, width=w, height=h, mask="auto")
            text_x = x + w + 2.2 * mm
        except Exception:  # noqa: BLE001 - a missing logo never stops the document
            pass
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(text_x, 15 * mm, FOOTER)
    c.restoreState()


def render(title: str, body_text: str) -> bytes:
    """Render a plain text document (newline-separated, *bold* lines) to PDF bytes."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    x = 22 * mm
    y = height - 28 * mm

    c.setFont("Helvetica-Bold", 15)
    c.drawString(x, y, title)
    y -= 6 * mm
    c.setStrokeColorRGB(0.8, 0.8, 0.8)
    c.line(x, y, width - 22 * mm, y)
    y -= 8 * mm

    for raw in body_text.splitlines():
        if y < 25 * mm:                       # new page, each with its own footer
            _footer(c, x, mm)
            c.showPage()
            y = height - 28 * mm
        text, bold = _clean(raw)
        if not text.strip():
            y -= 4 * mm
            continue
        c.setFont("Helvetica-Bold" if bold else "Helvetica", 11 if bold else 10)
        c.drawString(x, y, text[:110])
        y -= 6 * mm

    _footer(c, x, mm)
    c.showPage()
    c.save()
    return buf.getvalue()
